name: type_token
description: >-
  Extend on dart `Type` for more helpful function.
version: 1.0.5
homepage: https://github.com/Arxing/dart-type_token
author: Arxing <meiswind711108@gmail.com>
pubpage: https://pub.dev/packages/type_token

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  path: ^1.6.0
  useful_extension: any
  analyzer: ^0.39.7

dev_dependencies:
#  pedantic: ^1.7.0
#  test: ^1.6.0
